### ISSUE TITLE
InvalidArgumentError: Negative dimension size caused by subtracting 2 from 1 for 'max_pooling2d_10/MaxPool' (op: 'MaxPool') with input shapes: [?,1,112,128]

### ISSUE THREAD

**Issue by ragvri** [roebius/deeplearning1_keras2#5]
When I run the lesson1 notebook, I get the above mentioned error. Quick google search brought me [here](https://stackoverflow.com/questions/39815518/keras-maxpooling2d-layer-gives-valueerror). How do I resolve this?

**Comment by roebius** [comment]
It looks like your Keras is set to use TensorFlow instead of Theano (part 1 notebooks use Theano).
One thing to check is the keras.json file in your .keras directory. I suggest you try modifying your keras.json using the "keras.json.for_Theano" template from my repo. This should hopefully solve the issue.

**Comment by ragvri** [comment]
It did not work.

**Comment by vteodorescu** [comment]
Find this line:
from keras import backend as K
and put after it: 
K.set_image_dim_ordering('th')

**Comment by roebius** [comment]
@ragvri 
In case you have not yet solved the issue (also using the alternative suggestion thanks to @vteodorescu) it would help to see a full error log + the actual Keras version + the keras.json file.
